/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { thingSchema } from './thingSchema.ts'
import { z } from 'zod'

export const getThingsQueryParamsSchema = z
  .object({
    limit: z.number().int().min(1).max(100).default(100).describe('Maximum number of things to return'),
    skip: z.number().int().min(0).default(0).describe('Number of things to skip'),
  })
  .optional()

/**
 * @description A list of things
 */
export const getThings200Schema = z.object({
  items: z.array(z.lazy(() => thingSchema)),
})

export const getThingsQueryResponseSchema = z.lazy(() => getThings200Schema)