/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetThingsQueryParams, GetThings200, GetThingsQueryResponse } from '../types/GetThings.ts'
import type { ToZod } from '@kubb/plugin-zod/utils'
import { thingSchema } from './thingSchema.ts'
import { z } from 'zod'

export const getThingsQueryParamsSchema = z
  .object({
    limit: z.number().int().min(1).max(100).default(100).describe('Maximum number of things to return'),
    skip: z.number().int().min(0).default(0).describe('Number of things to skip'),
  })
  .optional() as unknown as ToZod<GetThingsQueryParams>

/**
 * @description A list of things
 */
export const getThings200Schema = z.object({
  items: z.array(z.lazy(() => thingSchema)),
}) as unknown as ToZod<GetThings200>

export const getThingsQueryResponseSchema = z.lazy(() => getThings200Schema) as unknown as ToZod<GetThingsQueryResponse>