/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Thing } from '../types/Thing.ts'
import type { ToZod } from '@kubb/plugin-zod/utils'
import { z } from 'zod'

export const thingSchema = z.object({
  id: z.string().describe('The unique identifier for the thing'),
}) as unknown as ToZod<Thing>