/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Thing } from './Thing.ts'

export type GetThingsQueryParams = {
  /**
   * @description Maximum number of things to return
   * @minLength 1
   * @maxLength 100
   * @default 100
   * @type integer | undefined
   */
  limit?: number
  /**
   * @description Number of things to skip
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  skip?: number
}

/**
 * @description A list of things
 */
export type GetThings200 = {
  /**
   * @type array
   */
  items: Thing[]
}

export type GetThingsQueryResponse = GetThings200

export type GetThingsQuery = {
  Response: GetThings200
  QueryParams: GetThingsQueryParams
  Errors: any
}